version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_TOKEN="YOUR_MARZBAN_ADMIN_TOKEN"
      - API_URL="YOUR_MARZBAN_LINK"
  telegram_bot:
    build:
      context: ./telegram_bot
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:3000
      - BOT_TOKEN="YOUR_TG_BOT_TOKEN"