[project]
name = "marzban-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
